export const SWIPE_UP_THRESHOLD = 80;
export const WHEEL_NAVIGATION_THRESHOLD = 40;
export const WHEEL_NAVIGATION_COOLDOWN_MS = 700;
export const FLOATING_EMOJI_DURATION_MS = 3000;
export const PREFETCH_THRESHOLD = 3;
export const LIVE_TOAST_MIN_VIEWERS = 10;
export const LIVE_TOAST_INTERVAL_MS = 60_000;
